#!/bin/bash

game=Kolhoznik

set -ex

mkdir -p .adom.data

while :; do
    ./adom -l "$game" || exit 1

    if test -e .adom.data/savedg/*.svg; then
        break
    fi

    if test -e .adom.data~; then
        rm -rf .adom.data
        cp -r .adom.data~ .adom.data
    fi
done

rm -rf .adom.data~~
mv .adom.data~ .adom.data~~
cp -r .adom.data .adom.data~
