#!/bin/bash

game=Kolhoznik

set -ex

mkdir -p adom_data

while :; do
    ./adom -l "$game" || exit 1

    if test -e adom_data/savedg/*.svg; then
        break
    fi

    if test -e adom_data~; then
        rm -rf adom_data
        cp -r adom_data~ adom_data
    fi
done

rm -rf adom_data~~
mv adom_data~ adom_data~~
cp -r adom_data adom_data~
